### ISSUE TITLE
Improved player/game statistics

### ISSUE THREAD

**Issue by squidgetx** [Hanabi-Live/hanabi-live#1057]
Not sure if this has already been discussed before but I think it'd be cool to see some additional game statistics functionality, mostly to get a sense of how "hard" a deal is.
In "other games":
- sort table by score
- strikeout rate
- non-strikeout average score or histogram
- percentile rank for games you participated in

In profile:
- some kind of player percentile ranking per variant/player# combo. This could either just be max score or the aggregation of all percentile rankings for each game. 

I'm happy to contribute technically / submit a PR for this, just want to make sure it's something the community wants and Zamiell/other maintainers think is acceptable from a server load point of view (I don't think it should be too crazy, we can probably start with calculating stats on page request?)

**Comment by Zamiell** [comment]
>sort table by score

sorting it by score by default seems fine

> strikeout rate

trivial to add, sure

> non-strikeout average score or histogram

sounds interesting i guess, sure

> percentile rank for games you participated in

sure

> some kind of player percentile ranking per variant/player# combo. This could either just be max score or the aggregation of all percentile rankings for each game.

sure, sounds more difficult though

> I'm happy to contribute technically / submit a PR for this

go for it

historically, the "other scores" functionality has been a complete afterthought. its one of those things that seems pretty cool as a brand new user: "Wow, I can go and see how other players dealt with this really hard deal!"

But the reality is different: "Oh, it just looks like mostly everyone just terminated the game within the first couple moves. And the people who didn't terminate had drastically different games because of a slightly different discard in the opening part (e.g. the *butterfly-effect*), so comparing the games is next-to-pointless."

**Comment by iamwhoiamhahaha** [comment]
actually i had a idea few months ago but i wasn't sure if you're gonna accept it.

can you add the win rate (making maximum score) in each variant?
you can replace `25 / 25` with the win rate after the player completing the perfect score

**Comment by Zamiell** [comment]
> can you add the win rate (making maximum score) in each variant?

where

**Comment by iamwhoiamhahaha** [comment]
replace `15/15`, `20/20`, `25/25`, and `30/30`

**Comment by Zamiell** [comment]
where

**Comment by iamwhoiamhahaha** [comment]
![win_rate](https://user-images.githubusercontent.com/50160641/82111944-2a9e2400-977b-11ea-860d-ab967ef050cb.png)

**Comment by Zamiell** [comment]
@squidgetx are you still doing this?
