### ISSUE TITLE
when assigning letters for suit abbreviations, it should skip over d, a, r, k

### ISSUE THREAD

**Issue by mmelwen** [Hanabi-Live/hanabi-live#2046]
https://github.com/Zamiell/hanabi-live/blob/master/docs/FEATURES.md#card-identity-notes

according to that 

[any dark suit] | [the same as the "normal" version of the suit]
-- | --

so pink should be i and prism should be p (probably) 
I found out that d is working but I dont know why

**Comment by kernel18** [comment]
I've tried to edit cards in hypo, and effectively, it seems that in variants with both an pink and dark prism suit (e.g. Pink/Light Pink/Gray Pink & Dark Prism), `i` is assigned to pink (which is normal), and `d` is used for Dark Prism.
The reason is (imo) that `p` is assigned by default for purple (when there's a purple suit, of course) and assigned to regular prism (when `i` is already taken by a pink suit), and that's all. The game assign the first letter of the Dark Prism suit -- that is to say `d` -- because it don't consider Dark Prism cards as "regular" prism cards.

A good way to solve this imo is to change the letter used for prism ; I suggest using `s` when it's possible, and use `i` alternatively (in Ambiguous variants, for example)

**Comment by kernel18** [comment]
In fact, the use of the letter `d` flows from this 
> If there are two suits with the same abbreviation, the second suit abbreviation will be changed to be the left-most unused letter.
> For example, in "Rainbow & Muddy Rainbow (6 Suits)", muddy rainbow will have an abbreviation of "U".

So, if `i` is already used for pink, dark prism suit abbreviation will be changed to its left-most unused letter, i.e. `d`.
Consequently, the behavior you're describing is totally normal, and a little annoying -- this is understandable.

As I said, the better thing to do imo is to change prism abbreviation to `s`, to avoid conflicts with other special suits.

**Comment by Zamiell** [comment]
i'll rename this issue accordingly
