### ISSUE TITLE
[bug] Accepted character range for seed names

### ISSUE THREAD

**Issue by aliblong** [Hanabi-Live/hanabi-live#2173]
The server communicates that only [`-A-Za-z0-9`] are valid characters for seed names, but this replay shows that it was possible to use a `#` character in the name. And it causes some wonky stuff when looking at other scores, for example.

https://hanab.live/replay/507894

**Comment by DrAnax** [comment]
The given game's seed is p3v183s

@Zamiell not a bug

**Comment by Zamiell** [comment]
it seems that libster is correct:
```
hanabi=> select seed from games where id=507894;
    seed
-------------
 p3v183s#pgV
(1 row)
```

**Comment by Zamiell** [comment]
so the fix is to update the table name regex that checks for special characters i think

**Comment by DrAnax** [comment]
There are 5 games with seeds containing a hashtag.

![image](https://user-images.githubusercontent.com/2622043/149243080-e4d83e8e-376d-4f5d-8251-e81f4e3e64ec.png)

After a quick code study, I think these were created because of the game's name. So the solution is not to allow a game's name to start with `!seed` and contain a `#`

**Comment by Zamiell** [comment]
make it more restrictive:
if the start of the game name is "!seed ", then disallow all special characters except for hyphens

**Comment by DrAnax** [comment]
> make it more restrictive: if the start of the game name is "!seed ", then disallow all special characters except for hyphens

So, only alllow `-a-zA-Z0-9` ?

**Comment by Zamiell** [comment]
yeah, and if the game name starts with a bang
