### ISSUE TITLE
Make the random table name generator family-friendly

### ISSUE THREAD

**Issue by marissaquitt** [Hanabi-Live/hanabi-live#2657]
Accidental dirtiness from word combinations can't be avoided but it'd sure be nice to not have words like "blowjob" in the word list.

**Comment by timotree3** [comment]
there have been like 3 PRs removing dirty words and we've never removed them all. I think we need a fresh wordlist that includes only simple good words, rather than an exhaustive wordlist where dirty words are removed

**Comment by timotree3** [comment]
That's a nice list. Wanna just do that list but with words longer than 3 letters?

**Comment by Romain672** [comment]
Else, you can maybe goes in totally another area.
Per example, here is the list of Towns on the world:
http://www.geonames.org/advanced-search.html?q=&featureClass=P&startRow=0

**Comment by TheDaniMan** [comment]
I have unfortunately never noticed such words in my table names, but I am twelve and therefore appreciate seeing randomly generated dirty words in my lobbies.
Given how rarely they come up and how little impact they have, isn't it easier for you to either remake the lobby or intentionally name it something whenever you play with your family, rather than having to implement a solution to something that is hard for me to see as a problem?

**Comment by Zamiell** [comment]
dani's comment is a little rude, so i've marked it as off topic.
let's try to be very polite on these issue threads.

for now, I'll close this issue, see #2658
