### ISSUE TITLE
[f] and [cm] borders don't disappear when the game ends

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2761]

**Comment by Krycke** [comment]
This is a side effect from the feature to let spectators write [f] and [cm] notes. Is this definitely seen as a bug or can it be a feature? I can see that the original behavior in replays has been changed, but do we want that behavior to be changed back?

The fix itself shouldn't be too hard to implement, just add a "is Running" check in some places.

**Comment by Zamiell** [comment]
It's definitely a bug because the notes appear before they have been written which is visually noisy and confusing for the end user

**Comment by Krycke** [comment]
On that note, i have a half implemented test branch where i store which turn each part of a note is written, so that you can follow a review and see the development of the card as they were on this turn during the game. Making no spoilers in a review through notes.

I have stopped development of that feature, because i don't know if that's something that we want to have implemented. And i don't know when we want the feature to be be enabled. Of course it should be off when the game is running, and always on when you watch a review from the database, but I'm not sure if it's wishful to have during a post game review.

Anyway, if this is a feature we want enabled, it makes sense to let [f] affect a card in review, because then it will show the card as it was during the game. But as long as we don't have this feature, i agree with you that it might look messy to the end user.

**Comment by Zamiell** [comment]
we dont want to require end users to write the turn on the card, so that feature isn't helpful in the context of this issue

**Comment by Krycke** [comment]
My feature wouldn't require anything like that. If the feature is off, everything would look exactly as it is now, i just record in the background at which turn a note has been changed and to what. If the feature is on, the note updates to be as it was at this turn in the live game. With the feature on, you can watch a replay from the database and see the notes change exactly as they did, when they did, as if you were a spectator in the live game. 

I was tinkering with this feature after watching the tournaments @pianoblook was commenting this early fall/summer. He often commented a game that had already been played, and had to make sure not to hover over the notes on the cards, as they spoiled a lot of the future of the game.

So i thought of just adding a spoiler free mode and just make notes evolveion the replay as they did in the real game, only if the mode was enabled. But maybe this is something that could be quite nice in more situations.

**Comment by Zamiell** [comment]
> i just record in the background at which turn a note has been changed

Unfortunately that isn't helpful because the turn that the note was written almost never corresponds to the contents of the note, we went over this in the other thread about automated turn notes

**Comment by Zamiell** [comment]
There's no way to synchronize the two things without forcing the end user to do more work

**Comment by naomiburks** [comment]
I wonder if note timing would make sense to be implemented with the empathy keybind. Maybe the default could be to show all the notes normally, but whenever spacebar is pressed, make any notes written on a later turn disappear? It's not a perfect solution but could help with knowing approximately when notes became relevant without it looking like finesses were missed simply due to being marked 1-2 turns late.

**Comment by Krycke** [comment]
I've read some discussions about automatically adding turn numbers, but i don't see this as that at all. This just mimics the line play even during replay. The finesse note might be coming in 2 turns late, and during turn 25 you might have gone back to check that on turn 8 this can't be blue. During replay with this feature on that note will be updated with the information that you wrote on turn 25 about turn 8, just as it was during the live game as well. I think this feature is quite cool, because it even more helps the spectator to see when players are actually gathering information and how/when they make their deductions. Even when they take their mistakes and removes the information in a note, which might not be stored right now.

**Comment by timotree3** [comment]
most of the time when I'm writing a note, I'm in the replay on the turn where it should be added. I think that if we determine the turn that way, it will be a very good approximation of when the note originates, and if we find that it's still not accurate enough, we can always come back and implement @naomiburks's suggestion and have the originating turn ignored by default and only visible when empathy or some similar option is enabled.

**Comment by Zamiell** [comment]
> During replay with this feature on that note will be updated with the information that you wrote on turn 25 about turn 8

We've decided against this in the past, as it is a violation of privacy

**Comment by timotree3** [comment]
There's no expectation of privacy about when notes are added. Anybody spectating a game can see the notes being updated live

**Comment by Zamiell** [comment]
There's a substantial difference between a random spectator seeing an ephemeral note and said note being saved to the database for all eternity

**Comment by Krycke** [comment]
Aha right, it's a privacy concern, sad. Then i understand your argumentation of the "end user needs to do something" because you still want to end user to have the option to decide what is stored in the database.

I wonder then if we could find some middle ground. Say for example "note history of stored and visible during one week after the game is played, after that it's removed".  If so that would cover the tournament use case, most "convention questions" and other "help me figure out what to do on this turn"-questions which makes it easier for spectators to understand the player in the specific case. But still it won't be stored for eternity?

**Comment by timotree3** [comment]
I think another good option would be to have a similar UX to the auto-pipes on notes: a turn number is automatically written in the note, and you can delete it if you're worried about the privacy concern or the turn number is incorrect and you care. If we wanted to go even further with fancy UX, I think that the note UI could integrate turns even more: Instead of using pipes for each phase of information on a card, the note dialog could actually have rows representing the phases, each labelled with the relevant turn (and you can edit the turn labels if the heuristic picks the wrong one) I will try to create a mockup or prototype so y'all can see what I'm picturing

**Comment by Krycke** [comment]
I think this general idea is what James is against because it creates a lot of extra work for the end user having to edit the turn number all the time. Of course you could add a opt-in option, but i know James is generally against that as well, having to maintain all different lines of options.

**Comment by Zamiell** [comment]
> a turn number is automatically written in the note, and you can delete it if you're worried about the privacy concern or the turn number is incorrect and you care.

absolutely not
