### ISSUE TITLE
Client UI Bugged

### ISSUE THREAD

**Issue by kesslermaximilian** [Hanabi-Live/hanabi-live#2867]
Since ~30min, the client UI on the site seems to be bugged (possibly because of your refactors today?):

- When a card bombed, then the next discard (current best educated guess) also shows the animation of this card bombing
- When cards are animated onto the stacks, they seem to be under other stacks' cards
- I think we noticed some other glitches, not sure what exactly

**Comment by Zamiell** [comment]
last night i reverted the server to commit c9c3eae75822ade31626473903a50a9e9b7a72ac.

and i revert all of the refactoring commits, i will do them again but slower and wait a few days in between so that way we can try to narrow down where the problem exists.
(there were too many changes included in the refactoring to know where the bugs came from.)
